// src/server/services/exportService.ts
// Secure PDF & CSV Export Generation with V1 & Legacy Compatibility

import PDFDocument from "pdfkit";
import { stringify } from "csv-stringify/sync";
import { Writable } from "stream";
import { sanitizeCsvValue } from "./reportAccess";

/**
 * Normalize and clean string inputs for PDF generation:
 * - Truncates excessively long narrative to prevent buffer exploitation / layout breaks.
 * - Strips dangerous ASCII control characters while preserving valid newlines and tabs.
 * - Preserves readable Unicode characters.
 */
function cleanPdfText(val: unknown, maxLength = 3000): string {
  if (val === null || val === undefined) {
    return "";
  }
  let str = String(val);
  if (str.length > maxLength) {
    str = str.slice(0, maxLength) + "… [truncated]";
  }
  // Strip control characters (0x00-0x08, 0x0B, 0x0C, 0x0E-0x1F, 0x7F) while keeping \t (0x09), \n (0x0A), \r (0x0D)
  return str.replace(/[\x00-\x08\x0B\x0C\x0E-\x1F\x7F]/g, "");
}

export const generatePdfStream = (reportData: any, outputStream: Writable) => {
  const doc = new PDFDocument({ margin: 50 });
  doc.pipe(outputStream);

  const isV1 = reportData?.schemaVersion === 1;

  if (isV1) {
    const title = cleanPdfText(reportData?.report?.title || "EduWell Psych - Student Wellness Report", 150);
    const student = reportData?.student;
    const session = reportData?.academicSession;
    const period = reportData?.report?.reportingPeriod;
    const generatedBy = reportData?.generatedBy;
    const summary = reportData?.summary;

    // Header
    doc.fontSize(20).text(title, { align: "center" }).moveDown();

    // Student & Session Metadata
    doc
      .fontSize(11)
      .text(`Student: ${cleanPdfText(student?.firstName || "")} ${cleanPdfText(student?.lastName || "")} (Code: ${cleanPdfText(student?.studentCode || "N/A")})`)
      .text(`Class: ${cleanPdfText(student?.class || "N/A")} | Section: ${cleanPdfText(student?.section || "N/A")}`)
      .text(`Academic Session: ${cleanPdfText(session?.name || "N/A")} (${cleanPdfText(period?.startDate || "")} to ${cleanPdfText(period?.endDate || "")})`)
      .text(`Generated By: ${cleanPdfText(generatedBy?.displayName || "Staff")} (${cleanPdfText(generatedBy?.role || "USER")}) on ${cleanPdfText(reportData?.report?.generatedAt || "")}`)
      .moveDown();

    // Summary Section
    doc.fontSize(14).text("Executive Summary", { underline: true }).moveDown(0.25);
    doc
      .fontSize(10)
      .text(`Current Wellness Status: ${cleanPdfText(summary?.currentWellnessStatus || "Not Assessed")}`)
      .text(`Assessments: ${summary?.assessmentStatusCounts?.COMPLETED ?? reportData?.assessments?.length ?? 0} Completed (${summary?.assessmentStatusCounts?.IN_PROGRESS ?? 0} in progress)`)
      .text(`Observations Logged: ${summary?.observationCount ?? 0} | Interventions: ${summary?.interventionCount ?? 0}`)
      .moveDown();

    // Assessments Section
    if (Array.isArray(reportData?.assessments) && reportData.assessments.length > 0) {
      doc.fontSize(14).text("Assessments", { underline: true }).moveDown(0.25);
      reportData.assessments.forEach((asmt: any) => {
        const templateName = cleanPdfText(asmt?.templateName || "Standard Assessment", 100);
        const score = asmt?.overallScore !== null && asmt?.overallScore !== undefined ? String(asmt.overallScore) : "N/A";
        const attention = cleanPdfText(asmt?.attentionLevel || "NORMAL", 30);
        const compDate = asmt?.completedDate ? cleanPdfText(String(asmt.completedDate).split("T")[0]) : "N/A";

        doc
          .fontSize(11)
          .text(`Protocol: ${templateName} | Completed: ${compDate} | Score: ${score} | Attention: ${attention}`)
          .moveDown(0.25);

        // Clinical notes if authorized
        if (asmt?.professionalInterpretation) {
          doc.fontSize(9).text(`Interpretation: ${cleanPdfText(asmt.professionalInterpretation, 1000)}`).moveDown(0.15);
        }
        if (asmt?.recommendations) {
          doc.fontSize(9).text(`Recommendations: ${cleanPdfText(asmt.recommendations, 1000)}`).moveDown(0.15);
        }

        // Domain breakdown
        if (Array.isArray(asmt?.domains) && asmt.domains.length > 0) {
          asmt.domains.forEach((dr: any) => {
            const domainName = cleanPdfText(dr?.name || "Domain", 50);
            const dScore = dr?.score !== undefined ? String(dr.score) : "0";
            const maxScore = dr?.maxScore !== undefined ? String(dr.maxScore) : "0";
            const label = cleanPdfText(dr?.resultLabel || dr?.attentionLevel || "", 30);
            doc.fontSize(9).text(`  - ${domainName}: ${dScore} / ${maxScore} ${label ? `(${label})` : ""}`);
          });
        }
        doc.moveDown(0.5);
      });
      doc.moveDown();
    }

    // Observations Section
    const obsSummary = reportData?.observations;
    const obsItems = Array.isArray(obsSummary?.items) ? obsSummary.items : [];
    if (obsItems.length > 0) {
      doc.fontSize(14).text("Observations Log", { underline: true }).moveDown(0.25);
      obsItems.forEach((obs: any) => {
        const dateStr = obs?.observedAt ? cleanPdfText(String(obs.observedAt).split("T")[0]) : "N/A";
        const source = cleanPdfText(obs?.source || "Staff", 30);
        const category = cleanPdfText(obs?.category || "General", 30);
        const narrative = cleanPdfText(obs?.observation || "", 2000);

        doc
          .fontSize(10)
          .text(`[${dateStr}] (${source} / ${category})`)
          .text(`Observation: ${narrative}`);

        if (obs?.psychologistNotes) {
          doc.text(`Psychologist Notes: ${cleanPdfText(obs.psychologistNotes, 1000)}`);
        }
        if (obs?.aiAnalysis) {
          doc.text(`AI Analysis: ${cleanPdfText(obs.aiAnalysis, 1000)}`);
        }

        doc.moveDown(0.35);
      });
      doc.moveDown();
    }

    // Interventions Section
    if (Array.isArray(reportData?.interventions) && reportData.interventions.length > 0) {
      doc.fontSize(14).text("Interventions Executed", { underline: true }).moveDown(0.25);
      reportData.interventions.forEach((inv: any) => {
        const dateStr = inv?.observedAt ? cleanPdfText(String(inv.observedAt).split("T")[0]) : "N/A";
        const category = cleanPdfText(inv?.category || "General", 30);
        const desc = cleanPdfText(inv?.intervention || "", 1000);

        doc.fontSize(9).text(`• [${dateStr}] (${category}): ${desc}`).moveDown(0.2);
      });
    }

    doc.end();
    return;
  }

  // ────────────────────────────────────────────────────────────
  // Legacy Report Format Handler (Backward Compatibility)
  // ────────────────────────────────────────────────────────────
  const title = cleanPdfText(reportData?.title || "EduWell Psych - Analytical Report", 150);
  const totalStudents = Number(reportData?.summary?.totalStudents ?? 0);
  const totalAssessments = Number(reportData?.summary?.totalAssessments ?? 0);
  const totalObservations = Number(reportData?.summary?.totalObservations ?? 0);

  doc.fontSize(20).text(title, { align: "center" }).moveDown();
  doc
    .fontSize(12)
    .text(`Total Students: ${totalStudents}`)
    .text(`Total Assessments: ${totalAssessments}`)
    .text(`Total Observations: ${totalObservations}`)
    .moveDown();

  // Legacy Assessments Section
  if (Array.isArray(reportData?.assessments) && reportData.assessments.length > 0) {
    doc.fontSize(16).text("Assessments Summary", { underline: true }).moveDown(0.5);
    reportData.assessments.forEach((assessment: any) => {
      const templateName = cleanPdfText(assessment?.assessmentTemplate?.name || assessment?.templateName || "Standard Assessment", 100);
      const score = cleanPdfText(assessment?.overallScore ?? "N/A", 20);
      const attention = cleanPdfText(assessment?.attentionLevel || "NORMAL", 30);

      doc
        .fontSize(12)
        .text(`Template: ${templateName} | Score: ${score} | Attention: ${attention}`)
        .moveDown(0.25);

      if (assessment?.professionalInterpretation) {
        doc.fontSize(10).text(`Interpretation: ${cleanPdfText(assessment.professionalInterpretation, 1000)}`).moveDown(0.25);
      }
      if (assessment?.recommendations) {
        doc.fontSize(10).text(`Recommendations: ${cleanPdfText(assessment.recommendations, 1000)}`).moveDown(0.25);
      }
      if (assessment?.clinicalNotes) {
        doc.fontSize(10).text(`Clinical Notes: ${cleanPdfText(assessment.clinicalNotes, 1000)}`).moveDown(0.25);
      }

      if (Array.isArray(assessment?.domainResults) && assessment.domainResults.length > 0) {
        assessment.domainResults.forEach((dr: any) => {
          const domainName = cleanPdfText(dr?.domain?.name || dr?.name || "Domain", 50);
          const dScore = cleanPdfText(dr?.score ?? "0", 10);
          const maxScore = cleanPdfText(dr?.maxScore ?? "0", 10);
          const label = cleanPdfText(dr?.resultLabel || "", 30);
          doc.fontSize(10).text(`  - ${domainName}: ${dScore} / ${maxScore} ${label ? `(${label})` : ""}`);
        });
      }
      doc.moveDown(0.5);
    });
    doc.moveDown();
  }

  // Legacy Observations Section
  const obsArray = Array.isArray(reportData?.observations)
    ? reportData.observations
    : Array.isArray(reportData?.observations?.items)
    ? reportData.observations.items
    : [];

  if (obsArray.length > 0) {
    doc.fontSize(16).text("Observations Summary", { underline: true }).moveDown(0.5);
    obsArray.forEach((obs: any) => {
      const dateStr = obs?.observedAt ? cleanPdfText(String(obs.observedAt).split("T")[0], 20) : "N/A";
      const source = cleanPdfText(obs?.source || "Staff", 30);
      const narrative = cleanPdfText(obs?.observation || "", 2000);

      doc
        .fontSize(10)
        .text(`Date: ${dateStr} | Source: ${source}`)
        .text(`Observation: ${narrative}`);

      if (obs?.psychologistNotes) {
        doc.text(`Psychologist Notes: ${cleanPdfText(obs.psychologistNotes, 1000)}`);
      }
      doc.moveDown(0.5);
    });
  }

  doc.end();
};

export const generateCsvString = (reportData: any): string => {
  const isV1 = reportData?.schemaVersion === 1;

  if (isV1) {
    const rows: Record<string, string>[] = [];
    const student = reportData?.student;
    const session = reportData?.academicSession;
    const summary = reportData?.summary;
    const assessments = Array.isArray(reportData?.assessments) ? reportData.assessments : [];
    const obsItems = Array.isArray(reportData?.observations?.items) ? reportData.observations.items : [];

    rows.push({
      RecordType: "SUMMARY",
      StudentID: sanitizeCsvValue(student?.studentCode),
      FirstName: sanitizeCsvValue(student?.firstName),
      LastName: sanitizeCsvValue(student?.lastName),
      Class: sanitizeCsvValue(student?.class),
      Section: sanitizeCsvValue(student?.section),
      AcademicSession: sanitizeCsvValue(session?.name),
      CurrentWellnessStatus: sanitizeCsvValue(summary?.currentWellnessStatus),
      CompletedAssessments: sanitizeCsvValue(summary?.assessmentStatusCounts?.COMPLETED ?? assessments.length),
      TotalObservations: sanitizeCsvValue(summary?.observationCount ?? obsItems.length),
      TotalInterventions: sanitizeCsvValue(summary?.interventionCount ?? 0),
      Detail: "",
    });

    assessments.forEach((asmt: any) => {
      rows.push({
        RecordType: "ASSESSMENT",
        StudentID: sanitizeCsvValue(student?.studentCode),
        FirstName: sanitizeCsvValue(student?.firstName),
        LastName: sanitizeCsvValue(student?.lastName),
        Class: sanitizeCsvValue(student?.class),
        Section: sanitizeCsvValue(student?.section),
        AcademicSession: sanitizeCsvValue(session?.name),
        CurrentWellnessStatus: sanitizeCsvValue(asmt?.attentionLevel),
        CompletedAssessments: sanitizeCsvValue(asmt?.templateName),
        TotalObservations: sanitizeCsvValue(asmt?.overallScore),
        TotalInterventions: sanitizeCsvValue(asmt?.completedDate),
        Detail: sanitizeCsvValue(asmt?.professionalInterpretation || ""),
      });
    });

    obsItems.forEach((obs: any) => {
      rows.push({
        RecordType: "OBSERVATION",
        StudentID: sanitizeCsvValue(student?.studentCode),
        FirstName: sanitizeCsvValue(student?.firstName),
        LastName: sanitizeCsvValue(student?.lastName),
        Class: sanitizeCsvValue(student?.class),
        Section: sanitizeCsvValue(student?.section),
        AcademicSession: sanitizeCsvValue(session?.name),
        CurrentWellnessStatus: sanitizeCsvValue(obs?.status),
        CompletedAssessments: sanitizeCsvValue(obs?.source),
        TotalObservations: sanitizeCsvValue(obs?.category),
        TotalInterventions: sanitizeCsvValue(obs?.observedAt),
        Detail: sanitizeCsvValue(obs?.observation || ""),
      });
    });

    return stringify(rows, { header: true });
  }

  // Legacy CSV generation
  const rows: Record<string, string>[] = [];
  const students: any[] = Array.isArray(reportData?.students) ? reportData.students : [];
  const assessments: any[] = Array.isArray(reportData?.assessments) ? reportData.assessments : [];
  const observations: any[] = Array.isArray(reportData?.observations) ? reportData.observations : [];

  if (students.length > 0) {
    students.forEach((student: any) => {
      const studentAssessments = assessments.filter((a: any) => a.studentId === student.id);
      const studentObservations = observations.filter((o: any) => o.studentId === student.id);

      rows.push({
        StudentId: sanitizeCsvValue(student.studentId),
        FirstName: sanitizeCsvValue(student.firstName),
        LastName: sanitizeCsvValue(student.lastName),
        ClassId: sanitizeCsvValue(student.classId),
        SectionId: sanitizeCsvValue(student.sectionId),
        TotalAssessments: sanitizeCsvValue(studentAssessments.length),
        TotalObservations: sanitizeCsvValue(studentObservations.length),
      });
    });
  } else {
    // If no students array (e.g. single item), output single summary row
    rows.push({
      ReportTitle: sanitizeCsvValue(reportData?.title || "Report"),
      TotalAssessments: sanitizeCsvValue(assessments.length),
      TotalObservations: sanitizeCsvValue(observations.length),
    });
  }

  return stringify(rows, { header: true });
};
